# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--skip-string-normalization, --line-length=120]  # disable double quotes enforcing
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-print==3.1.4'
        ]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: [
          --line-length=120,
          --force-grid-wrap=0,
          --multi-line=3,
          --use-parentheses,
          --trailing-comma,
          --lines-between-types=1
        ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: ^v?env/
      - id: end-of-file-fixer
        exclude: ^v?env/
default_language_version:
  python: python3
